"""
Telemetry Configuration
-----------------------

OpenTelemetry export for agent observability.
Traces are generated by Agno (tracing=True) and exported to an OTLP
endpoint when OTEL_EXPORTER_OTLP_ENDPOINT is set.
"""

import logging
from os import getenv

logger = logging.getLogger(__name__)


def configure_telemetry() -> None:
    """Set up OTel export if OTEL_EXPORTER_OTLP_ENDPOINT is configured.

    Safe to call unconditionally — no-ops when endpoint is not set.
    """
    endpoint = getenv("OTEL_EXPORTER_OTLP_ENDPOINT")
    if not endpoint:
        return

    from opentelemetry import trace
    from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
    from opentelemetry.sdk.trace import TracerProvider
    from opentelemetry.sdk.trace.export import BatchSpanProcessor

    provider = TracerProvider()
    exporter = OTLPSpanExporter(endpoint=f"{endpoint}/v1/traces")
    provider.add_span_processor(BatchSpanProcessor(exporter))
    trace.set_tracer_provider(provider)
    logger.info("OpenTelemetry export configured: %s", endpoint)
